language: scala

scala:
  - 2.11.11
  - 2.12.7

jdk:
  - oraclejdk8
  - openjdk11

script:
  - sbt clean headerCheck coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
