language: scala

scala:
  - 2.12.11
  - 2.13.2

jdk:
  - openjdk8
  - openjdk11

script:
  - sbt clean headerCheck test

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
